version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    format: '{"level": "%(levelname)s", "message": "%(message)s"}'
handlers:
  default:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  default:
    level: INFO
    handlers:
      - access
    propagate: no
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
  propagate: no
